# Generated by Django 3.2.9 on 2021-12-30 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20211230_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('default', 'Padrão'), ('CA', 'Casamento'), ('PW', 'Pré-Wedding'), ('GE', 'Gestante'), ('CORP', 'Corporativa'), ('EI', 'Ensaios Individuais')], default='default', max_length=20)),
                ('fotos', models.ManyToManyField(to='core.Imagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
