# Generated by Django 3.2.9 on 2021-12-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211230_1920'),
        ('booking', '0002_auto_20211230_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_capa', to='core.imagem'),
        ),
    ]
