# Generated by Django 3.2.9 on 2021-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_imagem_disponivel_galeria'),
        ('booking', '0003_booking_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='core.Imagem'),
        ),
    ]
