# Generated by Django 3.2.9 on 2021-12-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comentario',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
    ]
