# Generated by Django 3.2.9 on 2021-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('motivo_orcamento', models.CharField(max_length=200)),
                ('onde_me_achou', models.CharField(max_length=200)),
                ('mensagem', models.TextField(max_length=255)),
            ],
        ),
    ]
