# Generated by Django 3.2.8 on 2021-10-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagem_foto'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='instagram_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram_2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram_3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram_4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram_5',
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='carrossel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_2', to='core.imagem'),
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='carrossel_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_3', to='core.imagem'),
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='carrossel_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_4', to='core.imagem'),
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='carrossel_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_5', to='core.imagem'),
        ),
        migrations.AlterField(
            model_name='home',
            name='carrossel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.carrossel'),
        ),
        migrations.AlterField(
            model_name='home',
            name='contato_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.imagem'),
        ),
        migrations.AlterField(
            model_name='home',
            name='profile_foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='core.imagem'),
        ),
        migrations.CreateModel(
            name='InstagramFeel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_1', to='core.imagem')),
                ('instagram_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_2', to='core.imagem')),
                ('instagram_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_3', to='core.imagem')),
                ('instagram_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_4', to='core.imagem')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='instagram_feels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.instagramfeel'),
        ),
    ]
