# Generated by Django 3.2.8 on 2021-10-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211023_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='instagram_feels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.instagramfeel'),
        ),
    ]
