# Generated by Django 3.2.9 on 2021-11-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_tipo'),
        ('home', '0003_alter_home_instagram_feels'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='frase_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frase_img', to='core.imagem'),
        ),
    ]
