# Generated by Django 3.2.9 on 2021-12-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_tipo'),
        ('home', '0010_rename_momento_1_momento_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momento',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='core.imagem'),
        ),
    ]
