# Generated by Django 3.2.8 on 2021-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='', verbose_name='foto')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
