# Generated by Django 3.2.9 on 2021-12-30 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='tipo',
            field=models.CharField(choices=[('default', 'Padrão'), ('CA', 'Casamento'), ('PW', 'Pré-Wedding'), ('GE', 'Gestante'), ('CORP', 'Corporativa'), ('EI', 'Ensaios Individuais')], default='default', max_length=20, verbose_name='Tipo'),
        ),
    ]
