# Generated by Django 3.2.9 on 2021-12-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211230_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='disponivel_galeria',
            field=models.BooleanField(default=True, verbose_name='Disponível para galeria?'),
        ),
    ]
