# Generated by Django 3.2.8 on 2021-10-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrossel_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_1', to='core.imagem')),
                ('carrossel_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_2', to='core.imagem')),
                ('carrossel_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_3', to='core.imagem')),
                ('carrossel_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_4', to='core.imagem')),
                ('carrossel_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrossel_5', to='core.imagem')),
            ],
            options={
                'verbose_name_plural': 'Carrosseis',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('imagem_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momento_1', to='core.imagem')),
                ('momento_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momento_2', to='core.imagem')),
                ('momento_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momento_3', to='core.imagem')),
                ('momento_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momento_4', to='core.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_resumo', models.TextField(verbose_name='Resumo')),
                ('carrossel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carrossel')),
                ('contato_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagem')),
                ('instagram_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_1', to='core.imagem')),
                ('instagram_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_2', to='core.imagem')),
                ('instagram_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_3', to='core.imagem')),
                ('instagram_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_4', to='core.imagem')),
                ('instagram_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_5', to='core.imagem')),
                ('momentos', models.ManyToManyField(to='home.Momento')),
                ('pacotes', models.ManyToManyField(to='home.Pacote')),
                ('profile_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.imagem')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
