# Generated by Django 3.2.9 on 2021-11-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_frase_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='tipo',
            field=models.CharField(choices=[('default', 'Padrão')], default='default', max_length=20, verbose_name='Tipo'),
        ),
    ]
