# Generated by Django 3.2.9 on 2021-12-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_tipo'),
        ('home', '0005_momento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramfeel',
            name='instagram_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_5', to='core.imagem'),
        ),
    ]
