# Generated by Django 3.2.9 on 2021-12-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_instagramfeel_instagram_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramfeel',
            name='instagram_5',
        ),
    ]
