# Generated by Django 3.2.9 on 2021-12-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_momento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momento',
            old_name='momento_1',
            new_name='capa',
        ),
    ]
