# Generated by Django 3.2.9 on 2021-12-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_momento_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momento',
            name='momento_2',
        ),
        migrations.RemoveField(
            model_name='momento',
            name='momento_3',
        ),
        migrations.RemoveField(
            model_name='momento',
            name='momento_4',
        ),
    ]
