# Generated by Django 3.2.9 on 2021-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211229_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momento',
            name='tipo',
            field=models.CharField(choices=[('default', 'Padrão'), ('CA', 'Casamento'), ('PW', 'Pré-Wedding'), ('GE', 'Gestante'), ('CORP', 'Corporativa'), ('EI', 'Ensaios Individuais')], default='default', max_length=20, verbose_name='Tipo'),
        ),
    ]
