# Generated by Django 3.2.9 on 2021-12-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211230_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='momentos',
        ),
    ]
