# Generated by Django 3.2.9 on 2021-12-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_home_momentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='pacotes',
        ),
        migrations.DeleteModel(
            name='Pacote',
        ),
    ]
