# Generated by Django 3.2.9 on 2021-11-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagem_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='tipo',
            field=models.CharField(blank=True, choices=[('casamento', 'Casamento'), ('prewedding', 'Pré Wedding'), ('aniversario', 'Aniversário'), ('formatura', 'Formatura'), ('estudio', 'Estúdio')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
